### ISSUE TITLE
Example erroneously passes a boolean to the constructor.

### ISSUE THREAD

**Issue by inveteratus** [dopesong/Slim-Whoops#4]
The initial example shows a boolean being passed to the constructor:
```
$container['phpErrorHandler'] = $container['errorHandler'] = function($c) {
    return new WhoopsError($c->get('settings')['displayErrorDetails']);
};
```

While the constructor itself has no parameters.

I'd suggest the minor change to the example:
```
$container['phpErrorHandler'] = $container['errorHandler'] = function($c) {
    return new WhoopsError();
};
```

However this does raise the question, how best to display the whoops error page versus an end-user safe 500 status page on error without the ability to control the display mechanism in the constructor.

**Comment by dopesong** [comment]
Good catch. That's left from previous version https://github.com/dopesong/Slim-Whoops/blob/1.x/src/Whoops.php#L48

It was removed because no information was displayed at all when `['displayErrorDetails']` was false.

The best bet would be to introduce few new custom handlers which respects `displayErrorDetails` setting.

PR always welcome.
